/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Overall system health check for database, Redis, and configuration.
         */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Database
         * @description Database health check with connectivity test.
         */
        get: operations["check_database_health_database_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/redis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Redis
         * @description Redis cache health check with connectivity test.
         */
        get: operations["check_redis_health_redis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check All Services
         * @description Comprehensive health check for all system components.
         */
        get: operations["check_all_services_health_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Simple ping endpoint to verify API is running.
         */
        get: operations["ping_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate user and return JWT token
         *
         *     - **username**: User's username
         *     - **password**: User's password
         *
         *     Returns JWT access token valid for 24 hours
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get current authenticated user information
         *
         *     Requires valid JWT token in Authorization header
         */
        get: operations["get_current_user_info_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change Password
         * @description Change current user's password
         *
         *     - **current_password**: Current password for verification
         *     - **new_password**: New password (must be different from current)
         *
         *     Requires valid JWT token in Authorization header
         */
        put: operations["change_password_auth_me_password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change Email
         * @description Change current user's email address
         *
         *     - **new_email**: New email address
         *     - **password**: Current password for verification
         *
         *     Requires valid JWT token in Authorization header
         *
         *     Note: If this is an admin user, the alert recipient email will also be updated
         */
        put: operations["change_email_auth_me_email_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discovery Api
         * @description Manually trigger full network discovery scan.
         */
        get: operations["discovery_api_device_discover_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Devices Endpoint
         * @description Get all devices with stable DTO response
         */
        get: operations["get_all_devices_endpoint_device__get"];
        put?: never;
        /**
         * Create Device Endpoint
         * @description Create a new device with optional SNMP validation.
         *
         *     By default (validate=True), the endpoint will attempt to reach the device
         *     via SNMP before adding it to prevent adding unreachable devices.
         *
         *     Set validate=false to skip validation (not recommended).
         */
        post: operations["create_device_endpoint_device__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Devices Endpoint
         * @description Get device by IP with stable DTO response
         */
        get: operations["get_devices_endpoint_device__ip__get"];
        put?: never;
        post?: never;
        /**
         * Delete Devices Endpoint
         * @description Delete a device and all its associated data
         */
        delete: operations["delete_devices_endpoint_device__ip__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}/thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Device Thresholds Batch
         * @description Batch update device thresholds. Only provided thresholds will be updated.
         */
        put: operations["update_device_thresholds_batch_device__ip__thresholds_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}/interface/{if_index}/threshold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Interface Threshold Endpoint
         * @description Update the discard rate threshold for a specific interface.
         *     Threshold is a percentage (0-100) of total traffic that triggers alerts.
         *     Example: 0.1 means alert when discard rate exceeds 0.1% of traffic.
         */
        put: operations["update_interface_threshold_endpoint_device__ip__interface__if_index__threshold_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}/maintenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Maintenance Mode
         * @description Enable or disable maintenance mode for a device to suppress all alerts.
         */
        put: operations["update_maintenance_mode_device__ip__maintenance_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}/alerts/{alert_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Manage Device Alert
         * @description Consolidated endpoint for managing device alert states.
         *
         *     Supports:
         *     - alert_type: cpu, memory, reachability
         *     - action: acknowledge, resolve
         *
         *     Request body:
         *     {
         *         "action": "acknowledge" | "resolve",
         *         "notes": "optional notes",
         *         "reason": "optional reason (for resolve)"
         *     }
         */
        patch: operations["manage_device_alert_device__ip__alerts__alert_type__patch"];
        trace?: never;
    };
    "/device/{ip}/interfaces/{if_index}/alerts/{alert_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Manage Interface Alert
         * @description Consolidated endpoint for managing interface alert states.
         *
         *     Supports:
         *     - alert_type: status, drops
         *     - action: acknowledge, resolve
         *
         *     Request body:
         *     {
         *         "action": "acknowledge" | "resolve",
         *         "notes": "optional notes",
         *         "reason": "optional reason (for resolve)"
         *     }
         */
        patch: operations["manage_interface_alert_device__ip__interfaces__if_index__alerts__alert_type__patch"];
        trace?: never;
    };
    "/alerts/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Alert History
         * @description Get paginated alert history with optional filters.
         *
         *     Query parameters:
         *     - alert_type: cpu, memory, reachability, interface_status, packet_drop
         *     - severity: Warning, High, Critical
         *     - device_id: Filter by specific device
         *     - interface_id: Filter by specific interface
         *     - start_time: ISO 8601 timestamp
         *     - end_time: ISO 8601 timestamp
         *     - include_cleared: Whether to include cleared alerts (default: true)
         *     - page: Page number (default: 1)
         *     - per_page: Items per page (default: 50, max: 500)
         */
        get: operations["get_alert_history_alerts_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/history/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Alert History Detail
         * @description Get detailed information for a specific alert history record.
         */
        get: operations["get_alert_history_detail_alerts_history__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/history/device/{ip}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device Alert History
         * @description Get alert history for a specific device by IP address.
         */
        get: operations["get_device_alert_history_alerts_history_device__ip__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/history/device/{ip}/interfaces/{if_index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Interface Alert History
         * @description Get alert history for a specific interface.
         */
        get: operations["get_interface_alert_history_alerts_history_device__ip__interfaces__if_index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/history/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Alert History Stats
         * @description Get alert history statistics.
         */
        get: operations["get_alert_history_stats_alerts_history_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/polling/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Polling Status
         * @description Get current polling status and type.
         */
        get: operations["get_polling_status_polling_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/polling/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll All Device Api
         * @description Manually trigger full device poll.
         */
        get: operations["poll_all_device_api_polling__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/network-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Network Summary
         * @description Get network summary with 30-second cache
         */
        get: operations["get_network_summary_query_network_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/device/{ip}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device Metrics History */
        get: operations["get_device_metrics_history_query_device__ip__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/device/{ip}/interfaces/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device Interface Summary
         * @description Get optimized interface summary (only essential fields).
         *     Includes calculated discard rate percentage using delta calculation.
         *     Reduces payload size by 60-80% compared to full interface metrics.
         */
        get: operations["get_device_interface_summary_query_device__ip__interfaces_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/top-devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Top Devices
         * @description Get top devices with 60-second cache
         */
        get: operations["get_top_devices_query_top_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/history/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get History For Report */
        post: operations["get_history_for_report_query_history_device_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/network-throughput": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Network Throughput */
        get: operations["get_network_throughput_query_network_throughput_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/device-utilization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device Utilization
         * @description Get per-device throughput and utilization metrics over time (time series).
         *
         *     Returns time series data for devices showing:
         *     - Throughput (bps) over time
         *     - Total capacity (sum of interface speeds)
         *     - Utilization percentages over time
         *
         *     Parameters:
         *     - minutes: Time range to fetch data for (e.g., 15, 30, 60)
         *     - interval_minutes: Data aggregation interval (e.g., 1, 5, 10)
         *
         *     Only includes devices with at least one interface that has known speed.
         *     Data points are ordered chronologically for time series visualization.
         */
        get: operations["get_device_utilization_query_device_utilization_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/alerts/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Active Alerts
         * @description Retrieve all active alerts from the system.
         */
        get: operations["get_active_alerts_query_alerts_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/report/network-throughput": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Network Throughput
         * @description Get network-wide throughput aggregated across all interfaces for report date range.
         *     Returns time series of total inbound/outbound bandwidth.
         */
        get: operations["get_report_network_throughput_query_report_network_throughput_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/report/device-utilization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Device Utilization
         * @description Get network-wide CPU/Memory utilization metrics for report date range.
         *     Returns time series of average and max utilization across all devices.
         */
        get: operations["get_report_device_utilization_query_report_device_utilization_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/report/packet-drops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Packet Drops
         * @description Get packet drop statistics by device for report date range.
         *     Returns devices with highest discard rates using delta-based calculation.
         *     Includes multicast and broadcast packets for accurate rate calculation.
         */
        get: operations["get_report_packet_drops_query_report_packet_drops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/report/uptime-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Uptime Summary
         * @description Get system uptime summary for report date range.
         *     Returns current uptime based on most recent reading, longest uptime device, and recently rebooted device.
         *
         *     Note: Uses the most recent uptime value within the date range, not average,
         *     because averaging uptime values across reboots produces meaningless results.
         */
        get: operations["get_report_uptime_summary_query_report_uptime_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/report/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Availability
         * @description Get device availability metrics for report date range.
         *     Returns availability percentage based on polling success rate.
         *
         *     Availability is calculated by comparing actual polls received vs expected polls.
         *     Expected polls = (time_range_minutes / polling_interval_minutes)
         *     Actual polls = count of DeviceMetric records (each represents a successful poll)
         */
        get: operations["get_report_availability_query_report_availability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Recipients
         * @description Retrieve all alert recipients.
         */
        get: operations["get_all_recipients_recipients__get"];
        put?: never;
        /**
         * Create Recipient
         * @description Create a new alert recipient.
         */
        post: operations["create_recipient_recipients__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipients/{recipient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Recipient
         * @description Delete a recipient by ID.
         */
        delete: operations["delete_recipient_recipients__recipient_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Application Settings
         * @description Get current application settings from database.
         *     If no settings exist in DB, create default settings from .env.
         */
        get: operations["get_application_settings_settings__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Application Settings
         * @description Update application settings. Only provided fields will be updated.
         */
        patch: operations["update_application_settings_settings__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveAlertResponse */
        ActiveAlertResponse: {
            /** Hostname */
            hostname: string;
            /** Ip Address */
            ip_address: string;
            /** Metric */
            metric: string;
            /** Current Value */
            current_value: string;
            /** Threshold */
            threshold: string;
            /**
             * State
             * @default triggered
             */
            state: string;
            /** Acknowledged At */
            acknowledged_at?: string | null;
            /** If Index */
            if_index?: number | null;
            /**
             * Severity
             * @default Warning
             */
            severity: string;
        };
        /**
         * AlertAction
         * @description Schema for consolidated alert management endpoint
         */
        AlertAction: {
            /**
             * Action
             * @description Action to perform: 'acknowledge' or 'resolve'
             */
            action: string;
            /**
             * Notes
             * @description Optional notes about the action
             */
            notes?: string | null;
            /**
             * Reason
             * @description Reason for resolving (only for resolve action)
             */
            reason?: string | null;
        };
        /**
         * AlertHistoryDetailResponse
         * @description Detailed alert history response with related entities.
         */
        AlertHistoryDetailResponse: {
            /** Id */
            id: number;
            /** Alert Type */
            alert_type: string;
            /** Severity */
            severity: string;
            /** Device Id */
            device_id: number;
            /** Interface Id */
            interface_id: number | null;
            /**
             * Triggered At
             * Format: date-time
             */
            triggered_at: string;
            /** Cleared At */
            cleared_at: string | null;
            /** Metric Value */
            metric_value: string;
            /** Threshold Value */
            threshold_value: string;
            /** Message */
            message: string | null;
            /** Email Sent */
            email_sent: boolean;
            /** Email Status */
            email_status: string | null;
            /** Email Sent At */
            email_sent_at: string | null;
            /** Email Recipients */
            email_recipients: string | null;
            /** Email Error */
            email_error: string | null;
            /** Action Taken */
            action_taken: string | null;
            /** Action At */
            action_at: string | null;
            /** Action By */
            action_by: number | null;
            /** Action Notes */
            action_notes: string | null;
        };
        /**
         * AlertHistoryResponse
         * @description Response schema for alert history records.
         */
        AlertHistoryResponse: {
            /** Id */
            id: number;
            /** Alert Type */
            alert_type: string;
            /** Severity */
            severity: string;
            /** Device Id */
            device_id: number;
            /** Interface Id */
            interface_id: number | null;
            /**
             * Triggered At
             * Format: date-time
             */
            triggered_at: string;
            /** Cleared At */
            cleared_at: string | null;
            /** Metric Value */
            metric_value: string;
            /** Threshold Value */
            threshold_value: string;
            /** Message */
            message: string | null;
            /** Email Sent */
            email_sent: boolean;
            /** Email Status */
            email_status: string | null;
            /** Email Sent At */
            email_sent_at: string | null;
            /** Action Taken */
            action_taken: string | null;
            /** Action At */
            action_at: string | null;
            /** Action By */
            action_by: number | null;
            /** Action Notes */
            action_notes: string | null;
        };
        /**
         * AlertHistoryStatsResponse
         * @description Statistics for alert history.
         */
        AlertHistoryStatsResponse: {
            /** Total Alerts */
            total_alerts: number;
            /** Active Alerts */
            active_alerts: number;
            /** Cleared Alerts */
            cleared_alerts: number;
            /** Critical Count */
            critical_count: number;
            /** High Count */
            high_count: number;
            /** Warning Count */
            warning_count: number;
            /** Email Sent Count */
            email_sent_count: number;
            /** Email Failed Count */
            email_failed_count: number;
        };
        /** AlertStateResponse */
        AlertStateResponse: {
            /**
             * Message
             * @description Response message
             */
            message: string;
            /**
             * State
             * @description Current alert state (clear/triggered/acknowledged)
             */
            state: string;
            /**
             * Acknowledged At
             * @description When alert was acknowledged
             */
            acknowledged_at?: string | null;
        };
        /**
         * ApplicationSettingsResponse
         * @description Response schema for application settings
         */
        ApplicationSettingsResponse: {
            /** Id */
            id: number;
            /** Snmp Community */
            snmp_community: string;
            /** Snmp Timeout */
            snmp_timeout: number;
            /** Snmp Retries */
            snmp_retries: number;
            /** Polling Interval */
            polling_interval: number;
            /** Discovery Concurrency */
            discovery_concurrency: number;
            /** Polling Concurrency */
            polling_concurrency: number;
            /** Smtp Server */
            smtp_server: string;
            /** Smtp Port */
            smtp_port: number;
            /** Sender Email */
            sender_email: string | null;
            /** Sender Password */
            sender_password: string | null;
            /** Discovery Network */
            discovery_network: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ApplicationSettingsUpdate
         * @description Update schema for application settings - all fields optional
         */
        ApplicationSettingsUpdate: {
            /** Snmp Community */
            snmp_community?: string | null;
            /** Snmp Timeout */
            snmp_timeout?: number | null;
            /** Snmp Retries */
            snmp_retries?: number | null;
            /** Polling Interval */
            polling_interval?: number | null;
            /** Discovery Concurrency */
            discovery_concurrency?: number | null;
            /** Polling Concurrency */
            polling_concurrency?: number | null;
            /** Smtp Server */
            smtp_server?: string | null;
            /** Smtp Port */
            smtp_port?: number | null;
            /** Sender Email */
            sender_email?: string | null;
            /** Sender Password */
            sender_password?: string | null;
            /** Discovery Network */
            discovery_network?: string | null;
        };
        /**
         * AvailabilityRecord
         * @description Device availability metrics for reports
         */
        AvailabilityRecord: {
            /** Device Hostname */
            device_hostname: string;
            /** Device Ip */
            device_ip: string;
            /** Availability Pct */
            availability_pct: number;
            /** Avg Uptime Days */
            avg_uptime_days: number;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
        };
        /**
         * ChangeEmailRequest
         * @description Change email request
         */
        ChangeEmailRequest: {
            /**
             * New Email
             * Format: email
             */
            new_email: string;
            /**
             * Password
             * @description Current password for verification
             */
            password: string;
        };
        /**
         * ChangePasswordRequest
         * @description Change password request
         */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** DeviceInfo */
        DeviceInfo: {
            /**
             * Ip Address
             * @description Device IP address
             */
            ip_address: string;
            /**
             * Hostname
             * @description Device system name
             * @default Unknown
             */
            hostname: string;
            /**
             * Mac Address
             * @description Device MAC address
             */
            mac_address: string;
            /**
             * Vendor
             * @description Vendor
             * @default N/A
             */
            vendor: string;
            /**
             * Priority
             * @description Priority
             * @default 1
             */
            priority: number;
            /** Last Poll Attempt */
            last_poll_attempt?: string | null;
            /** Last Poll Success */
            last_poll_success?: string | null;
            /**
             * Consecutive Failures
             * @default 0
             */
            consecutive_failures: number;
            /**
             * Is Reachable
             * @default true
             */
            is_reachable: boolean;
            /**
             * Cpu Threshold
             * @default 80
             */
            cpu_threshold: number;
            /**
             * Memory Threshold
             * @default 80
             */
            memory_threshold: number;
            /**
             * Failure Threshold
             * @default 3
             */
            failure_threshold: number;
            /**
             * Cpu Alert State
             * @default clear
             */
            cpu_alert_state: string;
            /**
             * Memory Alert State
             * @default clear
             */
            memory_alert_state: string;
            /**
             * Reachability Alert State
             * @default clear
             */
            reachability_alert_state: string;
            /** Cpu Acknowledged At */
            cpu_acknowledged_at?: string | null;
            /** Memory Acknowledged At */
            memory_acknowledged_at?: string | null;
            /** Reachability Acknowledged At */
            reachability_acknowledged_at?: string | null;
            /**
             * Reachability Alert Sent
             * @default false
             */
            reachability_alert_sent: boolean;
            /**
             * Maintenance Mode
             * @default false
             */
            maintenance_mode: boolean;
            /** Maintenance Until */
            maintenance_until?: string | null;
            /** Maintenance Reason */
            maintenance_reason?: string | null;
            /**
             * Status
             * @default up
             */
            status: string;
        };
        /**
         * DeviceMetricResponse
         * @description For returning historical metric data for charts.
         */
        DeviceMetricResponse: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Cpu Utilization */
            cpu_utilization: number;
            /** Memory Utilization */
            memory_utilization: number;
            /** Uptime Seconds */
            uptime_seconds: number;
        };
        /**
         * DeviceResponse
         * @description DTO for device responses - stable API contract
         */
        DeviceResponse: {
            /** Id */
            id: number;
            /** Ip Address */
            ip_address: string;
            /** Hostname */
            hostname: string;
            /** Vendor */
            vendor: string | null;
            /** Is Reachable */
            is_reachable: boolean;
            /** Cpu Threshold */
            cpu_threshold: number;
            /** Memory Threshold */
            memory_threshold: number;
            /** Failure Threshold */
            failure_threshold: number;
            /** Cpu Alert State */
            cpu_alert_state: string;
            /** Memory Alert State */
            memory_alert_state: string;
            /** Reachability Alert State */
            reachability_alert_state: string;
            /** Maintenance Mode */
            maintenance_mode: boolean;
            /** Last Poll Success */
            last_poll_success: string | null;
        };
        /**
         * DeviceUtilizationDatapoint
         * @description Per-device throughput and utilization metrics.
         */
        DeviceUtilizationDatapoint: {
            /** Device Id */
            device_id: number;
            /** Hostname */
            hostname: string | null;
            /** Ip Address */
            ip_address: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Inbound Bps */
            inbound_bps: number;
            /** Outbound Bps */
            outbound_bps: number;
            /** Total Capacity Bps */
            total_capacity_bps: number | null;
            /** Utilization In Pct */
            utilization_in_pct: number | null;
            /** Utilization Out Pct */
            utilization_out_pct: number | null;
            /** Max Utilization Pct */
            max_utilization_pct: number | null;
        };
        /** DiscoveryResponse */
        DiscoveryResponse: {
            /**
             * Total Scanned
             * @description Total IPs scanned
             */
            total_scanned: number;
            /**
             * Devices Found
             * @description Number of responsive devices
             */
            devices_found: number;
            /**
             * Devices
             * @description List of discovered devices
             */
            devices: components["schemas"]["DeviceInfo"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response model
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Details
             * @default {}
             */
            details: {
                [key: string]: unknown;
            };
        };
        /** HistoryQuery */
        HistoryQuery: {
            /** Ip Address */
            ip_address: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
        };
        /**
         * InterfaceSummaryResponse
         * @description Lightweight interface data (only fields used by frontend)
         */
        InterfaceSummaryResponse: {
            /** If Index */
            if_index: number;
            /** If Name */
            if_name: string;
            /** If Descr */
            if_descr: string | null;
            /** Oper Status */
            oper_status: number;
            /** Admin Status */
            admin_status: number;
            /** Octets In */
            octets_in: number | null;
            /** Octets Out */
            octets_out: number | null;
            /** Discards In */
            discards_in: number | null;
            /** Discards Out */
            discards_out: number | null;
            /** Errors In */
            errors_in: number | null;
            /** Errors Out */
            errors_out: number | null;
            /** Packet Drop Threshold */
            packet_drop_threshold: number;
            /** Discard Rate Pct */
            discard_rate_pct?: number | null;
            /** Error Rate Pct */
            error_rate_pct?: number | null;
        };
        /** InterfaceThresholdResponse */
        InterfaceThresholdResponse: {
            /** Id */
            id: number;
            /** Device Id */
            device_id: number;
            /** If Index */
            if_index: number;
            /** If Name */
            if_name: string | null;
            /** Packet Drop Threshold */
            packet_drop_threshold: number;
        };
        /**
         * InterfaceThresholdUpdate
         * @description Schema for updating interface discard rate thresholds (percentage-based)
         */
        InterfaceThresholdUpdate: {
            /**
             * Threshold Value
             * @description Discard rate threshold (percentage: 0-100)
             */
            threshold_value: number;
        };
        /**
         * LoginRequest
         * @description Login request body
         */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MaintenanceModeUpdate */
        MaintenanceModeUpdate: {
            /**
             * Enabled
             * @description Enable/disable maintenance mode
             */
            enabled: boolean;
            /**
             * Duration Minutes
             * @description Maintenance window duration (1-1440 minutes)
             * @default 60
             */
            duration_minutes: number;
            /**
             * Reason
             * @description Reason for maintenance
             */
            reason?: string | null;
        };
        /**
         * MessageResponse
         * @description Generic message response
         */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * NetworkSummaryResponse
         * @description For the main dashboard's KPI cards.
         */
        NetworkSummaryResponse: {
            /** Total Devices */
            total_devices: number;
            /** Devices In Alert */
            devices_in_alert: number;
            /** Devices Up */
            devices_up: number;
            /** Devices Down */
            devices_down: number;
        };
        /**
         * NetworkThroughputDatapoint
         * @description Network-wide throughput data point for reports
         */
        NetworkThroughputDatapoint: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Total Inbound Bps */
            total_inbound_bps: number;
            /** Total Outbound Bps */
            total_outbound_bps: number;
        };
        /**
         * PacketDropRecord
         * @description Packet drop statistics by device for reports
         */
        PacketDropRecord: {
            /** Device Hostname */
            device_hostname: string;
            /** Device Ip */
            device_ip: string;
            /** Discard Rate Pct */
            discard_rate_pct: number;
            /** Total Discards In */
            total_discards_in: number;
            /** Total Discards Out */
            total_discards_out: number;
            /** Total Errors In */
            total_errors_in: number;
            /** Total Errors Out */
            total_errors_out: number;
        };
        /** RecipientCreate */
        RecipientCreate: {
            /**
             * Email
             * @description Recipient email address
             */
            email: string;
        };
        /** RecipientResponse */
        RecipientResponse: {
            /**
             * Id
             * @description Recipient ID
             */
            id: number;
            /**
             * Email
             * @description Recipient email address
             */
            email: string;
        };
        /**
         * ReportDeviceUtilizationDatapoint
         * @description Network-wide CPU/Memory utilization for reports
         */
        ReportDeviceUtilizationDatapoint: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Avg Cpu Utilization */
            avg_cpu_utilization: number;
            /** Avg Memory Utilization */
            avg_memory_utilization: number;
            /** Max Cpu Utilization */
            max_cpu_utilization: number;
            /** Max Memory Utilization */
            max_memory_utilization: number;
            /** Devices Sampled */
            devices_sampled: number;
        };
        /**
         * ServiceStatus
         * @description Individual service status
         */
        ServiceStatus: {
            /** Service */
            service: string;
            /** Status */
            status: string;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Response Time Ms
             * @default 0
             */
            response_time_ms: number;
        };
        /**
         * ThresholdBatchUpdate
         * @description Batch threshold update matching frontend payload
         */
        ThresholdBatchUpdate: {
            /** Cpu Threshold */
            cpu_threshold?: number | null;
            /** Memory Threshold */
            memory_threshold?: number | null;
            /** Failure Threshold */
            failure_threshold?: number | null;
        };
        /** ThroughputDatapoint */
        ThroughputDatapoint: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Inbound Bps */
            inbound_bps: number;
            /** Outbound Bps */
            outbound_bps: number;
        };
        /**
         * TokenResponse
         * @description JWT token response
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * TopDeviceResponse
         * @description For the dashboard bar charts.
         */
        TopDeviceResponse: {
            /** Hostname */
            hostname: string;
            /** Ip Address */
            ip_address: string;
            /** Value */
            value: number;
        };
        /**
         * UptimeSummaryResponse
         * @description System uptime summary for reports
         */
        UptimeSummaryResponse: {
            /** Avg Uptime Days */
            avg_uptime_days: number;
            /** Longest Uptime */
            longest_uptime: {
                [key: string]: unknown;
            };
            /** Recently Rebooted */
            recently_rebooted: {
                [key: string]: unknown;
            };
        };
        /**
         * UserResponse
         * @description User information response
         */
        UserResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Is Admin */
            is_admin: boolean;
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    check_database_health_database_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"];
                };
            };
        };
    };
    check_redis_health_redis_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"];
                };
            };
        };
    };
    check_all_services_health_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ping_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    change_password_auth_me_password_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_email_auth_me_email_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discovery_api_device_discover_get: {
        parameters: {
            query?: {
                network?: string;
                subnet?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_devices_endpoint_device__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"][];
                };
            };
        };
    };
    create_device_endpoint_device__post: {
        parameters: {
            query?: {
                validate?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceInfo"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_devices_endpoint_device__ip__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_devices_endpoint_device__ip__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_device_thresholds_batch_device__ip__thresholds_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThresholdBatchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_interface_threshold_endpoint_device__ip__interface__if_index__threshold_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
                if_index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterfaceThresholdUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterfaceThresholdResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_maintenance_mode_device__ip__maintenance_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceModeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manage_device_alert_device__ip__alerts__alert_type__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
                alert_type: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manage_interface_alert_device__ip__interfaces__if_index__alerts__alert_type__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
                if_index: number;
                alert_type: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_history_alerts_history_get: {
        parameters: {
            query?: {
                /** @description Filter by alert type */
                alert_type?: string | null;
                /** @description Filter by severity */
                severity?: string | null;
                /** @description Filter by device ID */
                device_id?: number | null;
                /** @description Filter by interface ID */
                interface_id?: number | null;
                /** @description Filter alerts after this time */
                start_time?: string | null;
                /** @description Filter alerts before this time */
                end_time?: string | null;
                /** @description Include cleared alerts */
                include_cleared?: boolean;
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertHistoryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_history_detail_alerts_history__alert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertHistoryDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_alert_history_alerts_history_device__ip__get: {
        parameters: {
            query?: {
                alert_type?: string | null;
                start_time?: string | null;
                end_time?: string | null;
                include_cleared?: boolean;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertHistoryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_interface_alert_history_alerts_history_device__ip__interfaces__if_index__get: {
        parameters: {
            query?: {
                alert_type?: string | null;
                start_time?: string | null;
                end_time?: string | null;
                include_cleared?: boolean;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path: {
                ip: string;
                if_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertHistoryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_history_stats_alerts_history_stats_get: {
        parameters: {
            query?: {
                start_time?: string | null;
                end_time?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertHistoryStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_polling_status_polling_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    poll_all_device_api_polling__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_network_summary_query_network_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkSummaryResponse"];
                };
            };
        };
    };
    get_device_metrics_history_query_device__ip__metrics_get: {
        parameters: {
            query?: {
                minutes?: number;
                interval_minutes?: number;
            };
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceMetricResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_interface_summary_query_device__ip__interfaces_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterfaceSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_top_devices_query_top_devices_get: {
        parameters: {
            query: {
                metric: "cpu" | "memory";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopDeviceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_for_report_query_history_device_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoryQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceMetricResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_network_throughput_query_network_throughput_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThroughputDatapoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_utilization_query_device_utilization_get: {
        parameters: {
            query?: {
                minutes?: number;
                interval_minutes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceUtilizationDatapoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_alerts_query_alerts_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveAlertResponse"][];
                };
            };
        };
    };
    get_report_network_throughput_query_report_network_throughput_get: {
        parameters: {
            query: {
                start_date: string;
                end_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkThroughputDatapoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_device_utilization_query_report_device_utilization_get: {
        parameters: {
            query: {
                start_date: string;
                end_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDeviceUtilizationDatapoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_packet_drops_query_report_packet_drops_get: {
        parameters: {
            query: {
                start_date: string;
                end_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PacketDropRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_uptime_summary_query_report_uptime_summary_get: {
        parameters: {
            query: {
                start_date: string;
                end_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UptimeSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_availability_query_report_availability_get: {
        parameters: {
            query: {
                start_date: string;
                end_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_recipients_recipients__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipientResponse"][];
                };
            };
        };
    };
    create_recipient_recipients__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recipient_recipients__recipient_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipient_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_application_settings_settings__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationSettingsResponse"];
                };
            };
        };
    };
    update_application_settings_settings__patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
