/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Overall system health check
         *
         *     Returns the health status of all system components:
         *     - Database connectivity
         *     - Redis cache (if enabled)
         *     - System timestamp
         *
         *     Status codes:
         *     - 200: System is healthy
         *     - 503: System has issues (check details)
         */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Database
         * @description Database health check
         *
         *     Tests database connectivity and response time
         */
        get: operations["check_database_health_database_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/redis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Redis
         * @description Redis cache health check
         *
         *     Tests Redis connectivity and response time
         */
        get: operations["check_redis_health_redis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check All Services
         * @description Comprehensive health check for all services
         *
         *     Returns detailed status of all system components
         */
        get: operations["check_all_services_health_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Simple ping endpoint
         *
         *     Returns a simple response to verify the API is running
         */
        get: operations["ping_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate user and return JWT token
         *
         *     - **username**: User's username
         *     - **password**: User's password
         *
         *     Returns JWT access token valid for 24 hours
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get current authenticated user information
         *
         *     Requires valid JWT token in Authorization header
         */
        get: operations["get_current_user_info_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change Password
         * @description Change current user's password
         *
         *     - **current_password**: Current password for verification
         *     - **new_password**: New password (must be different from current)
         *
         *     Requires valid JWT token in Authorization header
         */
        put: operations["change_password_auth_me_password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change Email
         * @description Change current user's email address
         *
         *     - **new_email**: New email address
         *     - **password**: Current password for verification
         *
         *     Requires valid JWT token in Authorization header
         *
         *     Note: If this is an admin user, the alert recipient email will also be updated
         */
        put: operations["change_email_auth_me_email_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discovery Api
         * @description API Endpoint to manually trigger a full network discovery.
         */
        get: operations["discovery_api_device_discover_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Devices Endpoint
         * @description Get all devices with stable DTO response
         */
        get: operations["get_all_devices_endpoint_device__get"];
        put?: never;
        /** Create Device Endpoint */
        post: operations["create_device_endpoint_device__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Devices Endpoint
         * @description Get device by IP with stable DTO response
         */
        get: operations["get_devices_endpoint_device__ip__get"];
        put?: never;
        post?: never;
        /** Delete Devices Endpoint */
        delete: operations["delete_devices_endpoint_device__ip__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}/thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Device Thresholds Batch
         * @description Batch update all thresholds for a device.
         *
         *     This endpoint allows updating multiple thresholds in a single request,
         *     matching the frontend payload structure. Only provided thresholds will be updated.
         */
        put: operations["update_device_thresholds_batch_device__ip__thresholds_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}/interface/{if_index}/threshold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Interface Threshold Endpoint
         * @description Update the discard rate threshold for a specific interface.
         *     Threshold is a percentage (0-100) of total traffic that triggers alerts.
         *     Example: 0.1 means alert when discard rate exceeds 0.1% of traffic.
         */
        put: operations["update_interface_threshold_endpoint_device__ip__interface__if_index__threshold_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}/alert/cpu/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Acknowledge Cpu Alert
         * @description Acknowledge CPU alert to stop receiving notifications until recovery.
         */
        put: operations["acknowledge_cpu_alert_device__ip__alert_cpu_acknowledge_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}/alert/cpu/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Resolve Cpu Alert
         * @description Manually resolve CPU alert (mark as false positive or resolved).
         */
        put: operations["resolve_cpu_alert_device__ip__alert_cpu_resolve_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}/alert/memory/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Acknowledge Memory Alert
         * @description Acknowledge Memory alert to stop receiving notifications until recovery.
         */
        put: operations["acknowledge_memory_alert_device__ip__alert_memory_acknowledge_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}/alert/memory/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Resolve Memory Alert
         * @description Manually resolve Memory alert (mark as false positive or resolved).
         */
        put: operations["resolve_memory_alert_device__ip__alert_memory_resolve_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}/alert/reachability/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Acknowledge Reachability Alert
         * @description Acknowledge Reachability alert to stop receiving notifications until recovery.
         */
        put: operations["acknowledge_reachability_alert_device__ip__alert_reachability_acknowledge_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}/alert/reachability/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Resolve Reachability Alert
         * @description Manually resolve Reachability alert (mark as false positive or resolved).
         */
        put: operations["resolve_reachability_alert_device__ip__alert_reachability_resolve_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}/interface/{if_index}/alert/status/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Acknowledge Interface Status Alert
         * @description Acknowledge interface operational status alert.
         */
        put: operations["acknowledge_interface_status_alert_device__ip__interface__if_index__alert_status_acknowledge_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}/interface/{if_index}/alert/status/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Resolve Interface Status Alert
         * @description Manually resolve interface operational status alert.
         */
        put: operations["resolve_interface_status_alert_device__ip__interface__if_index__alert_status_resolve_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}/interface/{if_index}/alert/drops/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Acknowledge Interface Drops Alert
         * @description Acknowledge interface packet drop alert.
         */
        put: operations["acknowledge_interface_drops_alert_device__ip__interface__if_index__alert_drops_acknowledge_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}/interface/{if_index}/alert/drops/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Resolve Interface Drops Alert
         * @description Manually resolve interface packet drop alert.
         */
        put: operations["resolve_interface_drops_alert_device__ip__interface__if_index__alert_drops_resolve_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/{ip}/maintenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Maintenance Mode
         * @description Enable or disable maintenance mode for a device to suppress all alerts.
         */
        put: operations["update_maintenance_mode_device__ip__maintenance_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/polling/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll All Device Api
         * @description API Endpoint to manually trigger a full device poll.
         *     This is now a "dumb" wrapper that calls the polling service.
         */
        get: operations["poll_all_device_api_polling__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/network-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Network Summary
         * @description Get network summary with 30-second cache
         */
        get: operations["get_network_summary_query_network_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/device/{ip}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device Metrics History */
        get: operations["get_device_metrics_history_query_device__ip__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/device/{ip}/interfaces/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device Interface Summary
         * @description Get optimized interface summary (only essential fields).
         *     Reduces payload size by 60-80% compared to full interface metrics.
         */
        get: operations["get_device_interface_summary_query_device__ip__interfaces_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/top-devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Top Devices
         * @description Get top devices with 60-second cache
         */
        get: operations["get_top_devices_query_top_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/history/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get History For Report */
        post: operations["get_history_for_report_query_history_device_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/network-throughput": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Network Throughput */
        get: operations["get_network_throughput_query_network_throughput_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/alerts/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Active Alerts
         * @description Retrieve all active alerts from the system.
         */
        get: operations["get_active_alerts_query_alerts_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Recipients
         * @description Retrieve all alert recipients
         */
        get: operations["get_all_recipients_recipients__get"];
        put?: never;
        /**
         * Create Recipient
         * @description Create a new alert recipient
         */
        post: operations["create_recipient_recipients__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipients/{recipient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Recipient
         * @description Delete a recipient by ID
         */
        delete: operations["delete_recipient_recipients__recipient_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveAlertResponse */
        ActiveAlertResponse: {
            /** Hostname */
            hostname: string;
            /** Ip Address */
            ip_address: string;
            /** Metric */
            metric: string;
            /** Current Value */
            current_value: string;
            /** Threshold */
            threshold: string;
            /**
             * State
             * @default triggered
             */
            state: string;
            /** Acknowledged At */
            acknowledged_at?: string | null;
            /** If Index */
            if_index?: number | null;
        };
        /** AlertAcknowledge */
        AlertAcknowledge: {
            /**
             * Notes
             * @description Optional notes about acknowledgment
             */
            notes?: string | null;
        };
        /** AlertResolve */
        AlertResolve: {
            /**
             * Reason
             * @description Reason for resolving alert
             */
            reason?: string | null;
        };
        /** AlertStateResponse */
        AlertStateResponse: {
            /**
             * Message
             * @description Response message
             */
            message: string;
            /**
             * State
             * @description Current alert state (clear/triggered/acknowledged)
             */
            state: string;
            /**
             * Acknowledged At
             * @description When alert was acknowledged
             */
            acknowledged_at?: string | null;
        };
        /**
         * ChangeEmailRequest
         * @description Change email request
         */
        ChangeEmailRequest: {
            /**
             * New Email
             * Format: email
             */
            new_email: string;
            /**
             * Password
             * @description Current password for verification
             */
            password: string;
        };
        /**
         * ChangePasswordRequest
         * @description Change password request
         */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** DeviceInfo */
        DeviceInfo: {
            /**
             * Ip Address
             * @description Device IP address
             */
            ip_address: string;
            /**
             * Hostname
             * @description Device system name
             * @default Unknown
             */
            hostname: string;
            /**
             * Mac Address
             * @description Device MAC address
             */
            mac_address: string;
            /**
             * Vendor
             * @description Vendor
             * @default N/A
             */
            vendor: string;
            /**
             * Priority
             * @description Priority
             * @default 1
             */
            priority: number;
            /** Last Poll Attempt */
            last_poll_attempt?: string | null;
            /** Last Poll Success */
            last_poll_success?: string | null;
            /**
             * Consecutive Failures
             * @default 0
             */
            consecutive_failures: number;
            /**
             * Is Reachable
             * @default true
             */
            is_reachable: boolean;
            /**
             * Cpu Threshold
             * @default 80
             */
            cpu_threshold: number;
            /**
             * Memory Threshold
             * @default 80
             */
            memory_threshold: number;
            /**
             * Failure Threshold
             * @default 3
             */
            failure_threshold: number;
            /**
             * Cpu Alert State
             * @default clear
             */
            cpu_alert_state: string;
            /**
             * Memory Alert State
             * @default clear
             */
            memory_alert_state: string;
            /**
             * Reachability Alert State
             * @default clear
             */
            reachability_alert_state: string;
            /** Cpu Acknowledged At */
            cpu_acknowledged_at?: string | null;
            /** Memory Acknowledged At */
            memory_acknowledged_at?: string | null;
            /** Reachability Acknowledged At */
            reachability_acknowledged_at?: string | null;
            /**
             * Reachability Alert Sent
             * @default false
             */
            reachability_alert_sent: boolean;
            /**
             * Maintenance Mode
             * @default false
             */
            maintenance_mode: boolean;
            /** Maintenance Until */
            maintenance_until?: string | null;
            /** Maintenance Reason */
            maintenance_reason?: string | null;
            /**
             * Status
             * @default up
             */
            status: string;
        };
        /**
         * DeviceMetricResponse
         * @description For returning historical metric data for charts.
         */
        DeviceMetricResponse: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Cpu Utilization */
            cpu_utilization: number;
            /** Memory Utilization */
            memory_utilization: number;
            /** Uptime Seconds */
            uptime_seconds: number;
        };
        /**
         * DeviceResponse
         * @description DTO for device responses - stable API contract
         */
        DeviceResponse: {
            /** Id */
            id: number;
            /** Ip Address */
            ip_address: string;
            /** Hostname */
            hostname: string;
            /** Vendor */
            vendor: string | null;
            /** Is Reachable */
            is_reachable: boolean;
            /** Cpu Threshold */
            cpu_threshold: number;
            /** Memory Threshold */
            memory_threshold: number;
            /** Failure Threshold */
            failure_threshold: number;
            /** Cpu Alert State */
            cpu_alert_state: string;
            /** Memory Alert State */
            memory_alert_state: string;
            /** Reachability Alert State */
            reachability_alert_state: string;
            /** Maintenance Mode */
            maintenance_mode: boolean;
            /** Last Poll Success */
            last_poll_success: string | null;
        };
        /** DiscoveryResponse */
        DiscoveryResponse: {
            /**
             * Total Scanned
             * @description Total IPs scanned
             */
            total_scanned: number;
            /**
             * Devices Found
             * @description Number of responsive devices
             */
            devices_found: number;
            /**
             * Devices
             * @description List of discovered devices
             */
            devices: components["schemas"]["DeviceInfo"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response model
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Details
             * @default {}
             */
            details: {
                [key: string]: unknown;
            };
        };
        /** HistoryQuery */
        HistoryQuery: {
            /** Ip Address */
            ip_address: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
        };
        /**
         * InterfaceSummaryResponse
         * @description Lightweight interface data (only fields used by frontend)
         */
        InterfaceSummaryResponse: {
            /** If Index */
            if_index: number;
            /** If Name */
            if_name: string;
            /** If Descr */
            if_descr: string | null;
            /** Oper Status */
            oper_status: number;
            /** Admin Status */
            admin_status: number;
            /** Octets In */
            octets_in: number | null;
            /** Octets Out */
            octets_out: number | null;
            /** Discards In */
            discards_in: number | null;
            /** Discards Out */
            discards_out: number | null;
            /** Errors In */
            errors_in: number | null;
            /** Errors Out */
            errors_out: number | null;
            /** Packet Drop Threshold */
            packet_drop_threshold: number;
        };
        /** InterfaceThresholdResponse */
        InterfaceThresholdResponse: {
            /** Id */
            id: number;
            /** Device Id */
            device_id: number;
            /** If Index */
            if_index: number;
            /** If Name */
            if_name: string | null;
            /** Packet Drop Threshold */
            packet_drop_threshold: number;
        };
        /**
         * InterfaceThresholdUpdate
         * @description Schema for updating interface discard rate thresholds (percentage-based)
         */
        InterfaceThresholdUpdate: {
            /**
             * Threshold Value
             * @description Discard rate threshold (percentage: 0-100)
             */
            threshold_value: number;
        };
        /**
         * LoginRequest
         * @description Login request body
         */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MaintenanceModeUpdate */
        MaintenanceModeUpdate: {
            /**
             * Enabled
             * @description Enable/disable maintenance mode
             */
            enabled: boolean;
            /**
             * Duration Minutes
             * @description Maintenance window duration (1-1440 minutes)
             * @default 60
             */
            duration_minutes: number;
            /**
             * Reason
             * @description Reason for maintenance
             */
            reason?: string | null;
        };
        /**
         * MessageResponse
         * @description Generic message response
         */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * NetworkSummaryResponse
         * @description For the main dashboard's KPI cards.
         */
        NetworkSummaryResponse: {
            /** Total Devices */
            total_devices: number;
            /** Devices In Alert */
            devices_in_alert: number;
            /** Devices Up */
            devices_up: number;
        };
        /** RecipientCreate */
        RecipientCreate: {
            /**
             * Email
             * @description Recipient email address
             */
            email: string;
        };
        /** RecipientResponse */
        RecipientResponse: {
            /**
             * Id
             * @description Recipient ID
             */
            id: number;
            /**
             * Email
             * @description Recipient email address
             */
            email: string;
        };
        /**
         * ServiceStatus
         * @description Individual service status
         */
        ServiceStatus: {
            /** Service */
            service: string;
            /** Status */
            status: string;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Response Time Ms
             * @default 0
             */
            response_time_ms: number;
        };
        /**
         * ThresholdBatchUpdate
         * @description Batch threshold update matching frontend payload
         */
        ThresholdBatchUpdate: {
            /** Cpu Threshold */
            cpu_threshold?: number | null;
            /** Memory Threshold */
            memory_threshold?: number | null;
            /** Failure Threshold */
            failure_threshold?: number | null;
        };
        /** ThroughputDatapoint */
        ThroughputDatapoint: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Inbound Bps */
            inbound_bps: number;
            /** Outbound Bps */
            outbound_bps: number;
        };
        /**
         * TokenResponse
         * @description JWT token response
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * TopDeviceResponse
         * @description For the dashboard bar charts.
         */
        TopDeviceResponse: {
            /** Hostname */
            hostname: string;
            /** Ip Address */
            ip_address: string;
            /** Value */
            value: number;
        };
        /**
         * UserResponse
         * @description User information response
         */
        UserResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Is Admin */
            is_admin: boolean;
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    check_database_health_database_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"];
                };
            };
        };
    };
    check_redis_health_redis_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"];
                };
            };
        };
    };
    check_all_services_health_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ping_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    change_password_auth_me_password_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_email_auth_me_email_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discovery_api_device_discover_get: {
        parameters: {
            query?: {
                network?: string;
                subnet?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_devices_endpoint_device__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"][];
                };
            };
        };
    };
    create_device_endpoint_device__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceInfo"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_devices_endpoint_device__ip__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_devices_endpoint_device__ip__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_device_thresholds_batch_device__ip__thresholds_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThresholdBatchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_interface_threshold_endpoint_device__ip__interface__if_index__threshold_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
                if_index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterfaceThresholdUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterfaceThresholdResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_cpu_alert_device__ip__alert_cpu_acknowledge_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AlertAcknowledge"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_cpu_alert_device__ip__alert_cpu_resolve_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AlertResolve"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_memory_alert_device__ip__alert_memory_acknowledge_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AlertAcknowledge"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_memory_alert_device__ip__alert_memory_resolve_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AlertResolve"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_reachability_alert_device__ip__alert_reachability_acknowledge_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AlertAcknowledge"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_reachability_alert_device__ip__alert_reachability_resolve_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AlertResolve"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_interface_status_alert_device__ip__interface__if_index__alert_status_acknowledge_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
                if_index: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AlertAcknowledge"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_interface_status_alert_device__ip__interface__if_index__alert_status_resolve_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
                if_index: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AlertResolve"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_interface_drops_alert_device__ip__interface__if_index__alert_drops_acknowledge_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
                if_index: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AlertAcknowledge"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_interface_drops_alert_device__ip__interface__if_index__alert_drops_resolve_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
                if_index: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AlertResolve"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_maintenance_mode_device__ip__maintenance_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceModeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    poll_all_device_api_polling__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_network_summary_query_network_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkSummaryResponse"];
                };
            };
        };
    };
    get_device_metrics_history_query_device__ip__metrics_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceMetricResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_interface_summary_query_device__ip__interfaces_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ip: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterfaceSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_top_devices_query_top_devices_get: {
        parameters: {
            query: {
                metric: "cpu" | "memory";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopDeviceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_for_report_query_history_device_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoryQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceMetricResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_network_throughput_query_network_throughput_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThroughputDatapoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_alerts_query_alerts_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveAlertResponse"][];
                };
            };
        };
    };
    get_all_recipients_recipients__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipientResponse"][];
                };
            };
        };
    };
    create_recipient_recipients__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recipient_recipients__recipient_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipient_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
